# Possible Issues:
#
# .gradlw permission denied:
# git update-index --chmod=+x gradlew //http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied

language: android
jdk: oraclejdk8

android:

  components:
  - android-25
   - build-tools-25.0.2
  - extra-google-m2repository
  - extra-android-m2repository

  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

script:
    - ./gradlew clean assemble
