# Possible Issues:
#
# .gradlw permission denied:
# git update-index --chmod=+x gradlew //http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied

language: android
jdk: oraclejdk8

android:

  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - openssl aes-256-cbc -K $encrypted_376031a79878_key -iv $encrypted_376031a79878_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

script:
    - ./gradlew clean assemble
